function createfigure(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1,YMATRIX1,X2,YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 26-Nov-2007 19:59:36

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

% Create axes
axes1 = axes('Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([0 17.2]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot(X1,YMatrix1,'Marker','o','Parent',axes1);

% Create multiple lines using matrix input to plot
plot(X2,YMatrix2,'Marker','o','Parent',axes1);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

